---
- hosts: all
  become: true
  remote_user: ansible

  vars_files: vault.yml
  vars:
    ansible_become_password: '{{ my_become_password }}'
    CDN_PREFIX: "https://cdn-public.redhat.com/content/public/addon/dist"
    FTP_PREFIX: "https://ftp.redhat.com/pub/redhat"
    GPGKEY: "https://www.redhat.com/security/data/fd431d51.txt"
    SSLCERT: "https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem"
    rhc_organization: "{{ devsub_orgid }}"
    rhc_auth:
      activation_keys: 
        keys: 
          - "{{ devsub_act_key }}"
    rhc_insights:
      state: present
      remediation: true
      tags:
        group: conversion_demo
        location: lab
        description:
          - "{{ ansible_distribution }}"
          - demo
  roles:
### RHC roles is close but not fully working with CentOS and Oracle
### For now, explicitly call on subscription-manager and insights-client
#    - role: redhat.rhel_system_roles.rhc
#    - role: fedora.linux_system_roles.rhc
#      when: ansible_distribution_version >= '8.6'
#      ansible_os_family == "RedHat"

  pre_tasks:

    - name: Validate distribution
      fail:
        msg: "Distribution {{ ansible_distribution }} is not compatible with this conversion tooling.  Please read https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index#con_supported-conversion-paths_converting-from-a-linux-distribution-to-rhel"
      #ansible.builtin.meta: end_host
      when: ansible_distribution != 'CentOS' and ansible_distribution != 'OracleLinux' and ansible_distribution != 'AlmaLinux' and ansible_distribution != 'Rocky'

    - name: Validate Release Version
      fail:
        msg: "Distribution version {{ ansible_distribution_version }} is not a compatible version for this conversion tooling.  Please read https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index#con_supported-conversion-paths_converting-from-a-linux-distribution-to-rhel"
        #msg: "Distribution must be a compatible version of  CentOS/Oracle/Alma/Rocky Linux https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index#con_supported-conversion-paths_converting-from-a-linux-distribution-to-rhel"
      #ansible.builtin.meta: end_host
      #when: ansible_distribution_version != '7.9'
      when: ansible_distribution_version != '7.9' and ansible_distribution_version <= '8.4'

    - name: Download Red Hat GPG key
      get_url:
        url: "{{ GPGKEY }}"
        dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"

    - name: Creates /etc/rhsm/ca directory
      file:
        path: /etc/rhsm/ca/
        state: directory

    - name: Download Red Hat GPG key
      get_url:
        url: "{{ SSLCERT }}"
        dest: "/etc/rhsm/ca/redhat-uep.pem"

    - name: Download Convert2RHEL {{ ansible_distribution_major_version }} repository file
      get_url:
        # https://ftp.redhat.com/pub/redhat/convert2rhel/7/convert2rhel.repo
        # https://ftp.redhat.com/pub/redhat/convert2rhel8/8/convert2rhel.repo
        # https://ftp.redhat.com/pub/redhat/convert2rhel/8/convert2rhel.repo
        url: "{{ FTP_PREFIX }}/convert2rhel/{{ ansible_distribution_major_version }}/convert2rhel.repo"
        dest: "/etc/yum.repos.d/"
      when: ansible_distribution_major_version >= '7' and ansible_distribution_major_version <= '8'

    - name: Download Convert2RHEL {{ ansible_distribution_major_version }} repository file
      get_url:
        # https://ftp.redhat.com/pub/redhat/convert2rhel/7/convert2rhel.repo
        # https://ftp.redhat.com/pub/redhat/convert2rhel8/8/convert2rhel.repo
        # https://ftp.redhat.com/pub/redhat/convert2rhel/8/convert2rhel.repo
        url: "{{ FTP_PREFIX }}/convert2rhel/8/convert2rhel.repo"
        dest: "/etc/yum.repos.d/"
      when: ansible_distribution_major_version == '9'

    - name: Download Red Hat Client Tools 7 repository file
      get_url:
        # https://ftp.redhat.com/pub/redhat/client-tools/client-tools-for-rhel-7-server.repo
        url: "{{ FTP_PREFIX }}/client-tools/client-tools-for-rhel-{{ ansible_distribution_major_version }}-server.repo"
        dest: "/etc/yum.repos.d/"
      when: ansible_distribution_major_version == '7' and ansible_architecture == 'x86_64'

    - name: Download Red Hat Client Tools {{ ansible_distribution_major_version }} repository file
      get_url:
        # https://ftp.redhat.com/pub/redhat/client-tools/client-tools-for-rhel-8.repo
        url: "{{ FTP_PREFIX }}/client-tools/client-tools-for-rhel-{{ ansible_distribution_major_version }}.repo"
#        url: "https://ftp.redhat.com/redhat/client-tools/client-tools-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}.repo"
        dest: "/etc/yum.repos.d/"
      when: ansible_distribution_major_version >= '8'


    - name: Remove RHN client tools from Oracle Linux 
      yum:
        name:
          - rhn-*
          - rhnsd
          - rhnlib
          - yum-rhn-plugin
          - yum-rhn-plugin
        state: absent
      when: ansible_distribution == 'OracleLinux'

    - name: Install convert2rhel and client connect tools for RHEL 7
      yum:
        name:
          - insights-client
          - rhc
          - rhc-worker-script
          - subscription-manager
          - convert2rhel
        exclude: rhn-client-tools  # needed on oracle
        state: latest
      when: ansible_distribution_major_version == '7'

    - name: Install convert2rhel and client connect tools for RHEL "{{ ansible_distribution_major_version }}"
      yum:
        name:
          - insights-client
          - rhc
          - rhc-worker-playbook
          - subscription-manager
          - convert2rhel
        exclude: rhn-client-tools  # needed on oracle
        state: latest
      when: ansible_distribution_major_version == '8'

    - name: Install client connect tools for RHEL "{{ ansible_distribution_major_version }}"
      yum:
        name:
          - insights-client
          - rhc
          - rhc-worker-playbook
          - subscription-manager
        exclude: rhn-client-tools  # needed on oracle
        state: latest
      when: ansible_distribution_major_version == '9'

  tasks:
#    - name: Register to Red Hat Subscription Manager to access content
#      shell: '/usr/bin/subscription-manager register --org="{{ devsub_orgid }}" --activationkey="{{ devsub_act_key }}" '

#    - name: Register to Red Hat Insights to appear in Inventory
#      shell: /usr/bin/insights-client --register

#    - name: Enable Insights remote host configuration for Conversion experience
#      shell: /usr/bin/rhc connect
#
    - name: Connect to Red Hat and Insights with remote host configuration for Conversion experience
      shell: "/usr/bin/rhc connect --organization {{ devsub_orgid }} --activation-key {{ devsub_act_key }}"
#      when: ansible_distribution_version <= '8.6'
#
#      rhc connect --organization ID --activation-key KEY

    - name: Install convert2rhel and client connect tools for RHEL "{{ ansible_distribution_major_version }}"
      yum:
        name:
          - convert2rhel
        exclude: rhn-client-tools  # needed on oracle
        state: latest
      when: ansible_distribution_major_version == '9'



## NOTE 1: use the -y option to answer yes to all yes/no questions the 
## tool asks carefully and only after you have tested interactively to 
## ensure that there are not surprises within your environment.  Also 
## take care to read and follow all prerequisites and backup guidance documented at 
## https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index

## NOTE 2: the following command may take 20-40 minutes on average to 
## complete, depending on quantity of packages installed and speed of 
## network and storage.  This will need to be run in parallel from the 
## control node or Tower to effectively run against many systems.

#    - name: Convert the system to RHEL
#      shell: convert2rhel -o "{{ devsub_orgid }}" -k "{{ devsub_act_key }}" --debug -y

