- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars:
    CONTENT_PATH: /share/repos
    ISO_PATH: /share/ISO
    WWW_PATH: /var/www/html
    WWW_REPO: "{{ WWW_PATH }}/repos"
    USE_SELINUX: 1
    USE_FIREWALL: 1
    SYNC: 1
  vars_files:
    - rhel_releases.yaml

  tasks:

    - name: Refresh Subscription Manager
      shell: subscription-manager refresh

    - name: Get sslclientkey
      shell: ls /etc/pki/entitlement/*key.pem 
      register: result
    - set_fact: sslclientkey={{ result.stdout }}
    

    - name: Get sslclientcert
      shell: ls /etc/pki/entitlement/*.pem | grep -v key
      register: result
    - set_fact: sslclientcert={{ result.stdout }}

      
    - name:  Configure Mirror Content for RHEL 7 Extras
      yum_repository:
        name: rhel-7-server-extras-rpms
        description: Red Hat Enterprise Linux 7 Server Extras (RPMs)
        file: mirror-cdn-content
        metadata_expire: 86400
        sslclientcert: "{{ sslclientcert }}"
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/7/7Server/$basearch/extras/os
        ui_repoid_vars: basearch
        sslverify: 1
        sslclientkey:  "{{ sslclientkey }}"
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        enabled: 0
        sslcacert: /etc/rhsm/ca/redhat-uep.pem
        gpgcheck: 1
        state: present


    - name:  Configure Mirror Content for RHEL 7 Ansible 2
      yum_repository:
        name: rhel-7-server-ansible-2-rpms
        description: Red Hat Ansible Engine 2 RPMs for Red Hat Enterprise Linux 7 Server
        file: mirror-cdn-content
        metadata_expire: 86400
        sslclientcert:  "{{ sslclientcert }}"
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/7/7Server/$basearch/ansible/2/os
        ui_repoid_vars: basearch
        sslverify: 1
        sslclientkey:  "{{ sslclientkey }}"
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        enabled: 0
        sslcacert: /etc/rhsm/ca/redhat-uep.pem
        gpgcheck: 1
        state: present


    - name:  Configure Mirror Content for RHEL 7 Base
      yum_repository:
        name: rhel-{{ item.major }}.{{ item.minor }}-server-rpms
        description: Red Hat Enterprise Linux {{ item.major }}.{{ item.minor }} Server (RPMs)
        file: mirror-cdn-content
        metadata_expire: 86400
        sslclientcert:  "{{ sslclientcert }}"
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/{{ item.major }}/{{ item.major }}.{{ item.minor }}/$basearch/os
        ui_repoid_vars: basearch
        sslverify: 1
        sslclientkey:  "{{ sslclientkey }}"
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        enabled: 0
        sslcacert: /etc/rhsm/ca/redhat-uep.pem
        gpgcheck: 0
        state: present
      when: item.major == 7
      loop: "{{ RHEL_RELEASES }}"



    - name:  Configure Mirror Content for RHEL 7 Optional
      yum_repository:
        name: rhel-{{ item.major }}.{{ item.minor }}-server-optional-rpms
        description: Red Hat Enterprise Linux {{ item.major }}.{{ item.minor }} Server Optional (RPMs)
        file: mirror-cdn-content
        metadata_expire: 86400
        sslclientcert:  "{{ sslclientcert }}"
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/{{ item.major }}/{{ item.major }}.{{ item.minor }}/$basearch/optional/os
        ui_repoid_vars: basearch
        sslverify: 1
        sslclientkey:  "{{ sslclientkey }}"
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        enabled: 0
        sslcacert: /etc/rhsm/ca/redhat-uep.pem
        gpgcheck: 1
        state: present
      when: item.major == 7
      loop: "{{ RHEL_RELEASES }}"
      


    - name:  Configure Mirror Content for RHEL for SAP Applications
      yum_repository:
        file: mirror-cdn-content
        name: rhel-sap-for-rhel-{{ item.major }}.{{ item.minor }}-server-rpms
        description: Red Hat Enterprise Linux for SAP (RHEL {{ item.major }}.{{ item.minor }} Server) (RPMs)
        metadata_expire: 86400
        sslclientcert:  "{{ sslclientcert }}"
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/{{ item.major }}/{{ item.major }}.{{ item.minor }}/$basearch/sap/os
        ui_repoid_vars: basearch
        sslverify: 1
        sslclientkey:  "{{ sslclientkey }}"
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        enabled: 0
        sslcacert: /etc/rhsm/ca/redhat-uep.pem
        gpgcheck: 1
        state: present
      when: item.major == 7
      loop: "{{ RHEL_RELEASES }}"


    - name:  Configure Mirror Content for RHEL for SAP HANA Applications
      yum_repository:
        file: mirror-cdn-content
        name: rhel-sap-hana-for-rhel-{{ item.major }}.{{ item.minor }}-server-rpms
        description: Red Hat Enterprise Linux for SAP HANA (RHEL {{ item.major }}.{{ item.minor }} Server) (RPMs)
        metadata_expire: 86400
        sslclientcert:  "{{ sslclientcert }}"
        baseurl: https://cdn.redhat.com/content/dist/rhel/server/{{ item.major }}/{{ item.major }}.{{ item.minor }}/$basearch/sap-hana/os
        ui_repoid_vars: basearch
        sslverify: 1
        sslclientkey:  "{{ sslclientkey }}"
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        enabled: 0
        sslcacert: /etc/rhsm/ca/redhat-uep.pem
        gpgcheck: 1
        state: present
      when: item.major == 7
      loop: "{{ RHEL_RELEASES }}"


    - name:  Confirm apache and repo sync tools are installed
      yum: 
        name: httpd,createrepo,yum-utils,rsync
        state: installed

    - name: Sync RHEL 7 Repos
      #debug: 
      #  msg: " --download_path={{ CONTENT_PATH }} --repoid {{ item.1 }}  "
      command: "reposync --gpgcheck -ldn --download_path={{ CONTENT_PATH }} --repoid {{ item.1 }} --downloadcomps --download-metadata"
      when: 
        - SYNC
        - item.0.major == 7
      loop: "{{ RHEL_RELEASES|subelements('repos') }}"


    - name: Generate Repository Metadata
      #debug: 
      #  msg: " --download_path={{ CONTENT_PATH }} --repoid {{ item.1 }}  "
      command: "createrepo {{ CONTENT_PATH }}/{{ item.1 }} -g comps.xml"
      when: 
        - SYNC
        - item.0.major == 7
      loop: "{{ RHEL_RELEASES|subelements('repos') }}"

    - name: Create Symlink for /var/www/html/repos to content
      file: 
        src: "{{ CONTENT_PATH }}"
        dest: "{{ WWW_REPO }}"
        state: link
      when: CONTENT_PATH != WWW_REPO


    - name: Repo content ownership by apache
      file: 
        path: "{{ item }}" 
        recurse: yes 
        owner: apache 
        group: apache 
        mode: "u=rwX,g=rX,o=rX" 
        state: directory
      with_items:
        - "{{ CONTENT_PATH }}"
        #- /share/repos
       
    - name: Confirm SELinux labels
      include_role:
        name: rhel-system-roles.selinux
      vars:
        selinux_fcontexts:
          #- { target: '{{CONTENT_PATH}}(/.*)?', setype: 'httpd_sys_content_t', state: 'present' }
          - { target: '{{CONTENT_PATH}}(/.*)?', setype: 'public_content_t', state: 'present' }
        SELinux_restore_dirs:
          - "{{ CONTENT_PATH }}"
      when: USE_SELINUX


    - name: Configure Firewall for Apache
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: http
          state: enabled
      when: USE_FIREWALL
    


#    - name: Debug test repos list
#      debug:
#        msg: "MAJOR: {{ item.0.major }}  MINOR: {{ item.0.minor }}  REPO: {{ item.1 }}"
#      when: 
#        - SYNC
#        - item.0.major == 7
#      loop: "{{ RHEL_RELEASES|subelements('repos') }}"



#    - name: Create Extras Symlink
#      file: 
#        src: "{{ CONTENT_PATH }}/mirror-rhel-7-server-extras-rpms"  
#        dest: "{{ CONTENT_PATH }}/rhel-7-server-extras-rpms"
#        state: link

#    - name: Create Symlink for to mirror repo names
#      file: 
#        src: "{{ CONTENT_PATH }}/mirror-{{ item.1 }}"  
#        dest: "{{ CONTENT_PATH }}/{{ item.1 }}"
#        state: link
#      when: item.0.major == 7
#      loop: "{{ RHEL_RELEASES|subelements('repos') }}"

