- hosts: all
  remote_user: root

#  become: yes
#  become_method: sudo
#  become_user: root

# Assumes you are using RHEL System Roles
#   RHEL 7:  subscription-manager repos --enable=rhel-7-server-ansible-2-rpms
#   RHEL 8:  subscription-manager repos --enable=ansible-2-for-rhel-8-x86_64-rpms
#   yum install -y ansible rhel-system-roles
#
# Assumes roles from galaxy
#   ansible-galaxy install linux-system-roles.firewall
#   ansible-galaxy install linux-system-roles.cockpit

  vars:
    USE_FIREWALL: 1
#    cockpit_packages:
#      - cockpit-storaged
#      - cockpit-podman

  tasks:

    - name: Install RHEL/Fedora Web Console (Cockpit)
      include_role:
        name: linux-system-roles.cockpit
      vars:
#        cockpit_packages: "full"   # or minimal, default

    - name: Configure Firewall for Web Console
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: cockpit
          state: enabled
      when: USE_FIREWALL|bool

