- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars:
    #CONTENT_PATH: /home/tbowling/Downloads/repos
    #ISO_PATH: /home/tbowling/Downloads/ISOS
    CONTENT_PATH: /share
    ISO_PATH: /share/ISO
    WWW_PATH: /var/www/html
    WWW_REPO: "{{ WWW_PATH }}/repos"
    USE_SELINUX: 1
    USE_FIREWALL: 1
    SYNC: 0
  vars_files:
    - rhel_releases.yaml

  tasks:

    - name:  Confirm apache and repo sync tools are installed
      yum: 
        name: httpd,createrepo,yum-utils,rsync
        state: installed


    - name: Create repo directory
      file:
        path: "{{ WWW_REPO }}"
        state: directory


    - name: Create ISO Mount Directories
      file:
        path: "{{ WWW_PATH }}/ISO/{{ item.major }}.{{ item.minor }}"
        state: directory
        recurse: yes
      loop: "{{ RHEL_RELEASES }}"

       
    - name: Confirm SELinux labels
      include_role:
        name: rhel-system-roles.selinux
      vars:
        selinux_fcontexts:
          #- { target: '{{CONTENT_PATH}}(/.*)?', setype: 'httpd_sys_content_t', state: 'present' }
          - { target: '{{CONTENT_PATH}}(/.*)?', setype: 'public_content_t', state: 'present' }
        SELinux_restore_dirs:
          - "{{ ISO_PATH }}"
          #- "{{ CONTENT_PATH }}"
      when: USE_SELINUX


    - name: Mount ISO images
      mount:
        src: "{{ ISO_PATH }}/{{ item.iso }}"
        path: "{{ WWW_PATH }}/ISO/{{ item.major }}.{{ item.minor }}"
        opts: ro,loop
        fstype: iso9660
        state: mounted
      loop: "{{ RHEL_RELEASES }}"


    - name: Configure Firewall for Apache
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: http
          state: enabled
      when: USE_FIREWALL
    

