- hosts: all
  become: true
  remote_user: root

#  become: yes
#  become_method: sudo
#  become_user: root

  vars:
    LATESTVER: "0.18"
    LATESTBUILD: "1"
    GPGKEY: "https://www.redhat.com/security/data/fd431d51.txt"

  tasks:
    - include_vars: demo_vault.yml

    - name: Validate distribution (CentOS or Oracle Linux)
      meta: end_host
      when: ansible_distribution != 'CentOS' and ansible_distribution != 'OracleLinux'

    - name: Validate Release Version (6.10, 7.9, 8.3)
      meta: end_host
      when: ansible_distribution_version != '6.10' and ansible_distribution_version != '7.9' and ansible_distribution_version != '8.3'

    - name: Download Red Hat GPG key
      get_url:
        url: "{{ GPGKEY }}"
        dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"

     ## FUTURE FEATURE - currently empty
    - name: Define Convert2RHEL {{ ansible_distribution_major_version }} Repo
      yum_repository:
        name: convert2rhel
        description: Convert2RHEL $releasever repo
        baseurl: "http://ftp.redhat.com/pub/redhat/convert2rhel/$releasever/os/"
        enabled: no
        gpgcheck: yes

    - name: Install convert2rhel "{{ ansible_distribution_major_version }}"
      yum:
        name: 'https://github.com/oamg/convert2rhel/releases/download/v{{ LATESTVER }}/convert2rhel-{{ LATESTVER }}-{{ LATESTBUILD }}.el{{ ansible_distribution_major_version }}.noarch.rpm'
        #name: 'http://192.168.1.5/convert2rhel/convert2rhel-{{ LATESTVER }}-{{ LATESTBUILD }}.el{{ ansible_distribution_major_version }}.noarch.rpm'
        ## https://github.com/oamg/convert2rhel/releases/download/v0.18/convert2rhel-0.18-1.el8.noarch.rpm
        state: installed
        disable_gpg_check: yes

#    - name: Convert the system to RHEL
#      shell: convert2rhel -k "{{ rhsm_key }}" -o "{{ rhsm_org }}" --debug -y

