---
- hosts: all
  become: true
  remote_user: ansible
  #remote_user: tbowling

  vars_files: vault.yml
  vars:
    ansible_become_password: '{{ my_become_password }}'
    #ansible_become_password: "{{ install_password }}"

  roles:

  tasks:

    - name: Ping test
      ansible.builtin.ping:

    - name: Distribution
      debug: msg="{{ ansible_distribution }}"

    - name: OS Family
      debug: msg="{{ ansible_os_family }}"

    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"

    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"

    - name: Distribution Release
      debug: msg="{{ ansible_distribution_release }}"

    - name: Hostname
      debug: msg="{{ ansible_hostname }}"

    - name: Node name
      debug: msg="{{ ansible_nodename }}"

    - name: Distribution file path
      debug: msg="{{ ansible_distribution_file_path }}"

    - name: Distribution file variety
      debug: msg="{{ ansible_distribution_file_variety }}"

    - name: Interfaces
      debug: msg="{{ ansible_interfaces }}"

    - name: All IPv4 Addresses
      debug: msg="{{ ansible_all_ipv4_addresses }}"

    - name: All IPv6 Addresses
      debug: msg="{{ ansible_all_ipv6_addresses }}"

    - name: Default IPv4 
      debug: msg="{{ ansible_default_ipv4 }}"

#    - name: Distribution 
#      debug: msg="{{  }}"

#    - name: 
#      debug: msg="{{  }}"





