- hosts: all
  remote_user: root

#  become: yes
#  become_method: sudo
#  become_user: root

# Assumes you are using RHEL System Roles
#   subscription-manager repos --enable=rhel-7-server-ansible-2-rpms
#   subscription-manager repos --enable=ansible-2-for-rhel-8-x86_64-rpms
#   yum install -y ansible rhel-system-roles
#
# Assumes roles from galaxy
#   ansible-galaxy install linux-system-roles.storage
#   ansible-galaxy install linux-system-roles.firewall
#   ansible-galaxy install linux-system-roles.cockpit

  vars:
    USE_FIREWALL: 1
    CONFIG_STORAGE: 0

  tasks:
    # Optional example to configure a second disk for your node to contain
    # the OS image artifacts created.  Typical minimal images are ~ 2 GB each.
    # Another option is to simply link to a NAS share.
    - name: Configure storage for Image Builder
      include_role:
        name: linux-system-roles.storage
      vars:
        use_partitions: false
        #storage_safe_mode: false  # only to force changes to sizing
        storage_pools:
          - name: image_builder
            disks: ['vdb','vdc']  # something like vdb
            # type: lvm
            state: present
            volumes:
              - name: osbuild
                size: "20G"     # estimate depending on how many images are created
                # type: lvm
                # fs_type: xfs
                fs_label: "osbuild"
                mount_point: '/var/lib/osbuild-composer'
              - name: osbuild_cache
                size: "20G"     # estimate depending on how many images are created
                # type: lvm
                # fs_type: xfs
                fs_label: "osbuild_cache"
                mount_point: '/var/cache/osbuild-worker'
      when: CONFIG_STORAGE

# Optionally use the Cockpit role to install the full suite,
  # else the Image Builder role will install the minimal dependencies for GUI.
#    - name: Install and enable RHEL/Fedora Web Console (Cockpit) service
#      include_role:
#        name: linux-system-roles.cockpit
#      vars:
#        cockpit_packages: "full"   # or "minimal" or "default"
  
    - name: Install and enable RHEL/Fedora Image Builder service
      include_role:
        name: linux-system-roles.image_builder
      vars:
        ib_packages: "full"   # or "minimal" or "default"
  
    - name: Configure Firewall for Web Console
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: cockpit
          state: enabled
      when: USE_FIREWALL

