---
- name: task for leapp pre-upgrade assessment
  hosts: localhost
  # gather_facts: false
  become: true
  tasks:

    - name: Exit for non-eligible releases
      ansible.builtin.meta: end_host
      when: 
        - ansible_distribution_major_version <= '6'
        - ansible_distribution_major_version >= '9'
        - ansible_distribution == 'CentOS'
        - ansible_distribution == 'CentOSStream'
        - ansible_distribution == 'Rocky'
        - ansible_distribution == 'AlmaLinux'
        - ansible_distribution == 'Scientific'
        - ansible_distribution == 'Amazon'
        - ansible_distribution == 'OracleLinux'
    
    #- name: Safety checks for potential non-standard repos configured??
      #ansible.builtin.meta: end_host
      #when: 
      # - something
      # - something
    
    - name: Install Leapp from RHEL 7 Extras
      yum: 
        name: leapp-upgrade
        state: present # or latest if not disruptive with dependency updates
        enablerepo: rhel-7-server-extras-rpms
        when: ansible_distribution_major_version == '7'

    - name: Install Leapp on RHEL 8 or later
      yum: 
        name: leapp-upgrade
        state: present # or latest if not disruptive with dependency updates
        when: ansible_distribution_major_version >= '8'

    - name: Execute leapp pre-upgrade
      ansible.builtin.shell: '/usr/bin/leapp preupgrade'

    #- name: How to communicate to Insights that the assessment is complete?
      # something, something

    #  Insights Client may be a better way to collect the report file.
    #- name: Collect leapp report file
    #  ansible.builtin.fetch: '/var/log/leapp/leapp-report.txt'
    #  or
    #  ansible.builtin.slurp: '/var/log/leapp/leapp-report.txt'


