- hosts: all
  remote_user: root

#  become: yes
#  become_method: sudo
#  become_user: root

# Assumes you are using RHEL System Roles
#   subscription-manager repos --enable=rhel-7-server-ansible-2-rpms
#   subscription-manager repos --enable=ansible-2-for-rhel-8-x86_64-rpms
#   yum install -y ansible rhel-system-roles
#
# Assumes roles from galaxy
#   ansible-galaxy install linux-system-roles.storage

  vars:
    CONFIG_STORAGE: 1

  tasks:
    # Configure separate disk for Satellite workload data
    - name: Configure storage for Image Builder
      include_role:
        name: linux-system-roles.storage
      vars:
        use_partitions: false
        storage_pools:
          - name: SatData
            # disks: ['vdb']  # something like vdb
            disks: [''] 
            # type: lvm
            state: present
            volumes:

              - name: pulp_cache
                size: "20G"
                # type: lvm
                # fs_type: xfs
                fs_label: "pulp_cache"
                mount_point: '/var/cache/pulp'

              - name: pulp
                size: "300G"
                fs_label: "pulp"
                mount_point: '/var/lib/pulp'

              - name: mongodb
                size: "50G"
                fs_label: "mongodb"
                mount_point: '/var/lib/mongodb'

              - name:qpidd 
                size: "20G"
                fs_label: "qpidd"
                mount_point: '/var/lib/qpidd'

              - name: pgsql
                size: "25G"
                fs_label: "pgsql"
                mount_point: '/var/lib/pgsql'

              - name: squid
                size: "10G"
                fs_label: "squid"
                mount_point: '/var/spool/squid'

              - name: puppetlabs 
                size: "1G"
                fs_label: "puppetlabs"
                mount_point: '/opt/puppetlabs'
      when: CONFIG_STORAGE

