---
# Assumes roles from galaxy
#   RHEL:  yum install -y rhel-system-roles
#   Fedora: yum install -y linux-system-roles
#   ansible-galaxy install geerlingguy.repo-epel
#   --extra-vars “rhsm_org=<my_rh_org>” --extra-vars “rhsm_key=<my_activation_key>”
- hosts: all
  become: yes
  remote_user: ansible
  #remote_user: tbowling


  vars_files: vault.yml
  vars:
    USE_FIREWALL: 1
    USE_RHEL_Beta_REPOS: 0  # Assumes hypervisor has VPN configured
    ansible_become_password: '{{ my_become_password }}'
    firewall:
      - previous: replaced
      - service: cockpit
        state: enabled
        runtime: true
        permanent: true
      - service: ssh
        state: enabled
        runtime: true
        permanent: true
    cockpit_enabled: true
    cockpit_started: true
#    cockpit_packages: minimal

  pre_tasks:
  - name: What distro is this?
    debug:
      msg: "{{ ansible_distribution }}"

#  - name: Overide package vars when Oracle Linux
#    set_fact:
#      cockpit_packages: minimal
#    when: ansible_distribution == 'OracleLinux'

  roles:
    - geerlingguy.repo-epel
    - linux-system-roles.cockpit
    - linux-system-roles.firewall
#    - rhel-system-roles.cockpit
#    - rhel-system-roles.firewall

  tasks:
#    - name: Configure internal RHEL 8 Beta repos
#      include_tasks: 8beta-repos.yml
#      when: USE_RHEL_Beta_REPOS|bool

    - name: Packages I want to remove
      package:
        name:
          - gnome-clocks
          - gnome-boxes
          - gnome-weather
          - gnome-maps
          - gnome-calendar
          - gnome-contacts
        state: absent

    - name: Add packages I care about
      package:
        name: 
          - cockpit
          - cockpit-*
          - cowsay
          - vim-enhanced
          - bash-completion
          - spice-vdagent
          - qemu-guest-agent
          - pcp-zeroconf
        exclude: 
          - cockpit-kubernetes
          - cockpit-machines*
          - cockpit-tests
        state: present  # or use latest

    - name: Upgrade all packages
      #ansible.builtin.yum:
      ansible.builtin.package:
        name: '*'
        state: latest

