- hosts: all
  become: yes
  become_method: sudo
  become_user: root

  vars:
    use_partitions: false

  tasks:
    - name: Configure Composer Storage
      include_role:
        name: linux-system-roles.storage
      vars:
        storage_pools:
          - name: composer
            disks: ['vdb']
            # type: lvm
            state: present
            volumes:
              - name: composer
                size: "19.5G"
                # type: lvm
                # fs_type: xfs
                fs_label: "composer"
                mount_point: '/var/lib/lorax/composer'
      when: CONFIG_STORAGE

    - name: Install Composer & Cockpit packages
      yum:
        name: cockpit-composer, composer-cli, lorax-composer
        state: latest


    - name: Configure Firewall for Cockpit
      include_role:
        name: linux-system-roles.firewall
      vars:
        firewall:
          service: cockpit
          state: enabled
      when: USE_FIREWALL

    - name: Enable and Start Cockpit service
      service:
        name: cockpit.socket
        enabled: yes
        state: started

    - name: Enable and Start Composer service
      service:
        name: lorax-composer.service
        enabled: yes
        state: started

